name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: []

  workflow_dispatch:

jobs:
  pre-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: vet
        run: go vet ./...

      - name: test
        run: go test ./...

  build:
    runs-on: ubuntu-latest

    needs: pre-build

    strategy:
      matrix:
        target: [linux, windows, darwin]
        arch: [amd64, arm64]

    env:
      GOOS: ${{ matrix.target }}
      GOARCH: ${{ matrix.arch }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: build
        run: go build

      - name: create artifacts dir
        run: mkdir artifacts

      - name: copy settings
        run: cp settings_example.json artifacts/settings.json

      - name: copy static
        run: cp -r static artifacts/

      - name: copy MovieNight
        run: cp MovieNight* artifacts/

      - uses: actions/upload-artifact@v3
        with:
          name: MovieNight-${{ matrix.target }}-${{ matrix.arch }}
          if-no-files-found: error
          path: artifacts/*

  test-ui-unix:
    runs-on: ${{ matrix.os }}

    needs: build

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact: MovieNight-linux-amd64
          - os: macos-latest
            artifact: MovieNight-darwin-amd64

    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.artifact }}

      - name: test
        run: |
          chmod +x ./MovieNight
          ./MovieNight & cd _uitests && go test

  test-ui-windows:
    runs-on: windows-latest

    needs: build

    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v3
        with:
          name: MovieNight-windows-amd64

      - name: test
        run: |
          Start-Job { ./MovieNight.exe }
          cd _uitests
          go test
